apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-api
  labels:
    app: tickets-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tickets-api
  template:
    metadata:
      labels:
        app: tickets-api
    spec:
      containers:
        - name: tickets-api
          image: gabrielroque/tickets-api:latest
          ports:
            - containerPort: 5000
          env:
            - name: ConnectionStrings__TicketDB
              value: "Server=192.168.10.118,1433;Database=tickets;User Id=sa;Password=Pass@word;TrustServerCertificate=true;Max Pool Size=200;Connection Timeout=60;"
            - name: Kafka__Url
              value: "192.168.10.118:9092"
            - name: Jwt__Key
              value: "YcxjOMewdFfeZFQm5iGAYxTjR23Z93rLbyZucty3"
            - name: Jwt__Issuer
              value: "https://tickets-api"
            - name: Jwt__Audience
              value: "https://tickets-api"
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-api-service
spec:
  selector:
    app: tickets-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
