# gateway-api deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api
  labels:
    app: gateway-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-api
  template:
    metadata:
      labels:
        app: gateway-api
    spec:
      containers:
        - name: gateway-api
          image: gabrielroque/gateway-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "192.168.10.169"
            - name: DB_PORT
              value: "6432"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "pass@#word"
            - name: DB_NAME
              value: "gateway-api"
            - name: X_API_KEY
              value: "master_api_key"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-api-service
spec:
  selector:
    app: gateway-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP # <- Aqui muda de LoadBalancer para comunicação interna
---
# tickets-api deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-api
  labels:
    app: tickets-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tickets-api
  template:
    metadata:
      labels:
        app: tickets-api
    spec:
      containers:
        - name: tickets-api
          image: gabrielroque/tickets-api:latest
          ports:
            - containerPort: 5000
          env:
            - name: ConnectionStrings__TicketDB
              value: "Server=192.168.10.169,1433;Database=tickets;User Id=sa;Password=Pass@word;TrustServerCertificate=true;Max Pool Size=200;Connection Timeout=60;"
            - name: Kafka__Url
              value: "192.168.10.169:9092"
            - name: Jwt__Key
              value: "YcxjOMewdFfeZFQm5iGAYxTjR23Z93rLbyZucty3"
            - name: Jwt__Issuer
              value: "https://tickets-api"
            - name: Jwt__Audience
              value: "https://tickets-api"
            - name: GatewayApi__Url
              value: "http://gateway-api-service" # referência interna ao serviço
            - name: GatewayApi__XApiKey
              value: "master_api_key"
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-api-service
spec:
  selector:
    app: tickets-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
