version: "3.8"

services:      
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    networks: 
      - ticket-network
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
    driver: local
    
networks:
  ticket-network:
    driver: bridge
